#!/bin/bash

# IMPLEMENTATION GUIDE
# Complete step-by-step walkthrough

echo "================================"
echo "🌐 Translation System Setup"
echo "================================"
echo ""

echo "📋 STEP 1: UNDERSTAND THE STRUCTURE"
echo "   Files created:"
echo "   ✓ contexts/LanguageContext.tsx - Language management"
echo "   ✓ components/language-switcher.tsx - Toggle button"
echo "   ✓ hooks/useTranslation.ts - Easy access hook"
echo "   ✓ lib/translations.ts - Helpers"
echo "   ✓ public/locales/{en,km}.json - Translations"
echo "   ✓ scripts/translate.js - Batch translator"
echo ""

echo "📝 STEP 2: UPDATE NAVIGATION (CRITICAL)"
echo "   Option A: Copy new version"
echo "   $ cp components/navigation-new.tsx components/navigation.tsx"
echo ""
echo "   Option B: Manual merge"
echo "   - Import LanguageSwitcher"
echo "   - Add <LanguageSwitcher /> in nav"
echo ""

echo "🏠 STEP 3: UPDATE YOUR PAGES"
echo "   For each page file:"
echo ""
echo "   1. Add at top:"
echo "      'use client';"
echo "      import { useLanguage } from '@/contexts/LanguageContext';"
echo ""
echo "   2. In component:"
echo "      const { t } = useLanguage();"
echo ""
echo "   3. Replace text:"
echo "      BEFORE: <h1>Contact Us</h1>"
echo "      AFTER:  <h1>{t('contact.title')}</h1>"
echo ""

echo "📋 STEP 4: ADD TRANSLATIONS"
echo "   Edit public/locales/en.json"
echo "   Add your English content:"
echo ""
echo "   {"
echo "     \"myPage\": {"
echo "       \"title\": \"My Title\","
echo "       \"description\": \"My Description\""
echo "     }"
echo "   }"
echo ""

echo "🌍 STEP 5: BATCH TRANSLATE"
echo "   Run auto-translation:"
echo "   $ npm run translate"
echo ""
echo "   This creates Khmer translations automatically!"
echo ""

echo "🧪 STEP 6: TEST"
echo "   Start dev server:"
echo "   $ npm run dev"
echo ""
echo "   Then:"
echo "   1. Look for language switcher in nav"
echo "   2. Click to switch to Khmer"
echo "   3. Verify all text translates"
echo "   4. Reload page - language persists"
echo ""

echo "================================"
echo "✅ IMPLEMENTATION COMPLETE!"
echo "================================"
echo ""

echo "📚 DOCUMENTATION:"
echo "   - TRANSLATION_QUICKSTART.md - Start here!"
echo "   - SETUP_CHECKLIST.md - Detailed checklist"
echo "   - TRANSLATION_GUIDE.md - Complete reference"
echo ""

echo "⚡ QUICK START CHECKLIST:"
echo "   [ ] Update components/navigation.tsx"
echo "   [ ] Add useLanguage() to pages"
echo "   [ ] Add translations to en.json"
echo "   [ ] Run: npm run translate"
echo "   [ ] Test in browser"
echo ""

echo "🚀 You're ready to go!"
echo ""
