export interface Product {
  id: number;
  name: string;
  nameKey?: string;
  image: string;
  category: string;
  specs: string;
  specsKey?: string;
  price: string;
  priceKey?: string;
  description: string;
  descriptionKey?: string;
  features: string[];
  applications?: string[];
  technicalData?: string;
}

// ─── 6 categories matching the navigation exactly ─────────────────────────────

export const productData: Record<string, Product[]> = {
  "products.categories.pharma": [
    {
      id: 1,
      name: "Pharmaceutical and Health Care Material",
      nameKey: "products.items.pharmaMaterial.name",
      image: "/images/blog-pharma.png",
      category: "products.categories.pharma",
      specs: "99.8% purity, Ph.Eur standard",
      specsKey: "products.items.pharmaMaterial.specs",
      price: "Contact for quote",
      priceKey: "products.items.pharmaMaterial.price",
      description: "A raw or processed substance used in the manufacture of medicines, medical devices, supplements, and health care products.",
      descriptionKey: "products.items.pharmaMaterial.description",
      features: ["Ph.Eur certified", "99.8% purity", "Bulk availability", "FDA compliant"],
      applications: ["Tablet formulations", "Injectable solutions", "Antacids", "Buffering agents"],
      technicalData: "CAS: 144-55-8 | Molecular Weight: 84.01 g/mol | Appearance: White crystalline powder",
    },
    // {
    //   id: 2,
    //   name: "Sodium Stannate",
    //   image: "/images/blog-compliance.jpg",
    //   category: "products.categories.pharma",
    //   specs: "Industrial & pharmaceutical grade",
    //   price: "Contact for quote",
    //   description: "Premium sodium stannate for advanced pharmaceutical and chemical applications.",
    //   features: ["Multiple grades", "Consistent quality", "Competitive pricing", "Long shelf life"],
    //   applications: ["Electroplating", "Pharmaceutical intermediates", "Catalysts", "Ceramics"],
    //   technicalData: "CAS: 12058-66-1 | Molecular Weight: 266.73 g/mol | Purity: 98% min",
    // },
    // {
    //   id: 3,
    //   name: "Pharmaceutical Grade Sodium Hydroxide",
    //   image: "/images/blog-sustainable.jpg",
    //   category: "products.categories.pharma",
    //   specs: "USP/BP certified",
    //   price: "Contact for quote",
    //   description: "Pure sodium hydroxide for pharmaceutical and laboratory use.",
    //   features: ["USP certified", "High purity", "Safe packaging", "Bulk availability"],
    //   applications: ["pH adjustment", "API synthesis", "Cleaning validation", "Laboratory reagents"],
    //   technicalData: "CAS: 1310-73-2 | Molecular Weight: 40.00 g/mol | Assay: 98-100.5%",
    // },
  ],
  "products.categories.personalCare": [
    {
      id: 10,
      name: "Personal and Home Care Material",
      nameKey: "products.items.personalCareMaterial.name",
      image: "/images/cosmetic-care.png",
      category: "products.categories.personalCare",
      specs: "100% natural blend",
      specsKey: "products.items.personalCareMaterial.specs",
      price: "Contact for quote",
      priceKey: "products.items.personalCareMaterial.price",
      description: "A raw or processed substance used in formulating personal care products (skincare, haircare ,oral care) and home care products (detergents, cleaners, disinfectants). These materials provide cleansing, conditioning, and protective functions.",
      descriptionKey: "products.items.personalCareMaterial.description",
      features: ["Skin conditioning", "Light texture", "Antioxidant rich", "Sustainable sourced"],
      applications: ["Moisturizers", "Serums", "Body lotions", "Hair oils"],
      technicalData: "Natural oil blend | Non-comedogenic | Dermatologically tested",
    },
    // {
    //   id: 11,
    //   name: "Surfactant Blend for Shampoos",
    //   image: "/images/blog-compliance.jpg",
    //   category: "products.categories.personalCare",
    //   specs: "Mild and gentle",
    //   price: "Contact for quote",
    //   description: "Specialized surfactant blends for high-performance shampoo formulations.",
    //   features: ["Gentle cleansing", "Rich lather", "Hair conditioning", "pH balanced"],
    //   applications: ["Shampoos", "Body washes", "Facial cleansers", "Baby products"],
    //   technicalData: "Active matter: 30-40% | pH: 5.5-6.5 | Biodegradable",
    // },
    // {
    //   id: 12,
    //   name: "Home Care Disinfectant Base",
    //   image: "/images/blog-partnership.jpg",
    //   category: "products.categories.personalCare",
    //   specs: "Industrial strength",
    //   price: "Contact for quote",
    //   description: "Powerful disinfectant compounds for household cleaning products.",
    //   features: ["Antimicrobial action", "Fast acting", "Non-corrosive", "Safe formulation"],
    //   applications: ["Surface cleaners", "Floor disinfectants", "Bathroom cleaners", "Kitchen sprays"],
    //   technicalData: "Active ingredient: 5-10% | Contact time: 30 seconds",
    // },
  ],
  "products.categories.food": [
    {
      id: 7,
      name: "Food Product",
      nameKey: "products.items.foodProduct.name",
      image: "/images/food-product.png",
      category: "products.categories.food",
      specs: "Food grade certified",
      specsKey: "products.items.foodProduct.specs",
      price: "Contact for quote",
      priceKey: "products.items.foodProduct.price",
      description: "A finished, processed, or packaged item intended for human consumption that has undergone preparation, combination, or transformation from raw ingredients.",
      descriptionKey: "products.items.foodProduct.description",
      features: ["Natural origin", "Food safe", "Clean label", "Effective preservation"],
      applications: ["Bakery products", "Dairy items", "Beverages", "Meat preservation"],
      technicalData: "Natural origin | Shelf life: 24 months | Storage: Cool dry place",
    },
    {
      id: 8,
      name: "Food Ingredient",
      nameKey: "products.items.foodIngredient.name",
      image: "/images/food-ingredient.png",
      category: "products.categories.food",
      specs: "Stabilizing agent",
      specsKey: "products.items.foodIngredient.specs",
      price: "Contact for quote",
      priceKey: "products.items.foodIngredient.price",
      description: "Any substance that is added to food during production, processing, or preparation to achieve a desired effect such as preservation, flavor, texture, or appearance.",
      descriptionKey: "products.items.foodIngredient.description",
      features: ["Superior stability", "Homogeneous mixing", "Shelf stable", "Cost efficient"],
      applications: ["Carbonated drinks", "Juice concentrates", "Sports beverages", "Flavored milk"],
      technicalData: "HLB value: 12-15 | Particle size: < 2 microns",
    },
    // {
    //   id: 9,
    //   name: "Food Grade Thickening Agent",
    //   image: "/images/food-ingredients.jpg",
    //   category: "products.categories.food",
    //   specs: "All-natural source",
    //   price: "Contact for quote",
    //   description: "Natural thickening agents for soups, sauces, and beverages.",
    //   features: ["Clean label", "High viscosity", "Neutral taste", "Easy dispersion"],
    //   applications: ["Sauces and gravies", "Soups", "Desserts", "Dressings"],
    //   technicalData: "Viscosity: 500-2000 cP | pH stability: 3-9",
    // },
  ],
  "products.categories.chemical": [
    {
      id: 101,
      name: "Chemical",
      nameKey: "products.items.chemicalMaterial.name",
      image: "/images/chemical.png",
      category: "products.categories.chemical",
      specs: "Lab and industrial use",
      specsKey: "products.items.chemicalMaterial.specs",
      price: "Contact for quote",
      priceKey: "products.items.chemicalMaterial.price",
      description: "A substance with a defined molecular composition used in industrial processes, manufacturing, agriculture and research. Chemicals serve as raw materials, reagents, solvents, and intermediates across virtually all industries.",
      descriptionKey: "products.items.chemicalMaterial.description",
      features: ["High purity", "Safe handling", "Proper labeling", "Bulk orders"],
      applications: ["Extraction processes", "Cleaning agents", "Chemical synthesis", "Paint thinners"],
      technicalData: "Various grades available | Custom specifications on request",
    },
    // {
    //   id: 102,
    //   name: "Advanced Catalyst Material",
    //   image: "/images/pharma-materials.jpg",
    //   category: "products.categories.chemical",
    //   specs: "Reaction optimization",
    //   price: "Contact for quote",
    //   description: "Specialized catalysts for chemical reactions and industrial processes.",
    //   features: ["High efficiency", "Reusable", "Cost saving", "Proven results"],
    //   applications: ["Petrochemical refining", "Polymerization", "Hydrogenation", "Oxidation reactions"],
    //   technicalData: "Custom formulations | Surface area: 100-500 m²/g",
    // },
    // {
    //   id: 103,
    //   name: "Industrial Chemical Reagent",
    //   image: "/images/chemical-supply.jpg",
    //   category: "products.categories.chemical",
    //   specs: "Laboratory grade",
    //   price: "Contact for quote",
    //   description: "High-purity chemical reagents for industrial applications.",
    //   features: ["High purity", "Consistent quality", "Bulk availability", "Technical support"],
    //   applications: ["Quality control labs", "Research institutions", "Manufacturing QA", "Environmental testing"],
    //   technicalData: "Purity: > 99% | Available in various pack sizes",
    // },
  ],
  "products.categories.agro": [
    {
      id: 13,
      name: "Agro-Product",
      nameKey: "products.items.agroProduct.name",
      image: "/images/agro-product.png",
      category: "products.categories.agro",
      specs: "Customizable formulations",
      specsKey: "products.items.agroProduct.specs",
      price: "Contact for quote",
      priceKey: "products.items.agroProduct.price",
      description: "A raw or semi-processed product derived from agricultural activities including farming, forestry, and fisheries. Argo-products serve as food, medicinal, feed, fuel, and industrial raw materials for downstream processing.",
      descriptionKey: "products.items.agroProduct.description",
      features: ["Custom blending", "Quality assured", "Cost effective", "Regulatory compliant"],
      applications: ["Poultry farming", "Cattle nutrition", "Aquaculture", "Swine production"],
      technicalData: "Custom formulations available | Complies with regional feed regulations",
    },
    // {
    //   id: 14,
    //   name: "Growth Promoting Feed Mix",
    //   image: "/images/blog-market.jpg",
    //   category: "products.categories.agro",
    //   specs: "Tested for efficacy",
    //   price: "Contact for quote",
    //   description: "Scientifically formulated feed additives for optimal animal nutrition.",
    //   features: ["Performance tested", "Natural ingredients", "Bioavailable", "Shelf stable"],
    //   applications: ["Broiler growth", "Dairy enhancement", "Egg production", "Fish growth"],
    //   technicalData: "Bioavailability: > 90% | Shelf life: 18 months | GMP certified",
    // },
  ],
  "products.categories.packaging": [
    {
      id: 16,
      name: "Cosmetic and Food Packaging",
      nameKey: "products.items.packagingMaterial.name",
      image: "/images/cosmetic-and-food-packaging.png",
      category: "products.categories.packaging",
      specs: "Eco-friendly formulation",
      specsKey: "products.items.packagingMaterial.specs",
      price: "Contact for quote",
      priceKey: "products.items.packagingMaterial.price",
      description: "Containers and materials designed to hold, protect, and present cosmetic and food products. Packaging ensures product stability, hygiene, and brand appeal while enabling precise dispensing and consumer convenience.",
      descriptionKey: "products.items.packagingMaterial.description",
      features: ["Eco-friendly", "High strength", "Temperature resistant", "Recyclable"],
      applications: ["Compostable bags", "Food packaging", "Agricultural films", "Disposable items"],
      technicalData: "Biodegradation time: 6-12 months | Compostable certified",
    },
    // {
    //   id: 17,
    //   name: "High-Performance Plastic Resin",
    //   image: "/images/blog-tech.jpg",
    //   category: "products.categories.packaging",
    //   specs: "Industrial grade",
    //   price: "Contact for quote",
    //   description: "Premium plastic resins for demanding industrial applications.",
    //   features: ["High durability", "Chemical resistant", "Easy processing", "Cost effective"],
    //   applications: ["Industrial containers", "Automotive parts", "Consumer goods", "Electronics"],
    //   technicalData: "Melt flow index: 5-50 g/10min | Density: 0.9-1.4 g/cm³",
    // },
    // {
    //   id: 18,
    //   name: "Flexible Film Material",
    //   image: "/images/packaging.jpg",
    //   category: "products.categories.packaging",
    //   specs: "Multi-layer capability",
    //   price: "Contact for quote",
    //   description: "Versatile flexible film materials for flexible packaging solutions.",
    //   features: ["Excellent flexibility", "Barrier properties", "Printable surface", "UV resistant"],
    //   applications: ["Pouch packaging", "Lamination", "Shrink wrap", "Protective covers"],
    //   technicalData: "Thickness range: 20-200 microns | Tensile strength: > 30 MPa",
    // },
  ],
};

// Ordered exactly as they appear in the navigation dropdown
export const categories = [
  "products.categories.pharma",
  "products.categories.personalCare",
  "products.categories.food",
  "products.categories.chemical",
  "products.categories.agro",
  "products.categories.packaging",
] as const;

export type CategoryKey = (typeof categories)[number];

// Maps the nav href slug → category key
// e.g. "pharmaceutical-health-care" → "Pharmaceutical and health care"
export const SLUG_TO_CATEGORY: Record<string, string> = {
  "pharmaceutical-health-care": "products.categories.pharma",
  "personal-care-home-care": "products.categories.personalCare",
  "food-food-ingredient": "products.categories.food",
  chemical: "products.categories.chemical",
  "agro-product": "products.categories.agro",
  packaging: "products.categories.packaging",
};
